services:
  kafka:
    image: apache/kafka:4.3.1
    container_name: kafka
    hostname: kafka

    ports:
      - "9092:9092"

    environment:
      # KRaft
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9094
      # Listeners
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9093,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9093,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      # Topic configuration
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # Transactions
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list > /dev/null 2>&1"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s

  kafka-init:
    image: apache/kafka:4.3.1
    container_name: kafka-init

    depends_on:
      kafka:
        condition: service_healthy

    entrypoint: ["/bin/bash", "-c"]

    command:
      - |
        /opt/kafka/bin/kafka-topics.sh \
          --bootstrap-server kafka:9093 \
          --create \
          --if-not-exists \
          --topic orders \
          --partitions 3 \
          --replication-factor 1

        echo "Kafka initialization completed"
        echo "Topic 'orders' with 3 partitions is ready"

  schema-registry:
    image: confluentinc/cp-schema-registry:8.3.2
    container_name: schema-registry
    hostname: schema-registry
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9093
      SCHEMA_REGISTRY_SCHEMA_COMPATIBILITY_LEVEL: BACKWARD

  producer:
    build:
      context: .
      dockerfile: producer/Dockerfile
    container_name: producer
    depends_on:
      kafka-init:
        condition: service_completed_successfully
      schema-registry:
        condition: service_started
    command: ["sh", "-c", "sleep 10 && python producer.py"]

  consumer:
    build:
      context: .
      dockerfile: consumer/Dockerfile
    container_name: consumer
    depends_on:
      kafka-init:
        condition: service_completed_successfully
      schema-registry:
        condition: service_started
    command: ["sh", "-c", "sleep 10 && python consumer.py"]
    restart: unless-stopped